apiVersion: v1
kind: Service
metadata:
  name: social-platform-app
  namespace: social-app
spec:
  type: ClusterIP
  selector:
    app: social-platform-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
