spring:
  application:
    name: social-platform-app
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
