apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - horizontal-pod-autoscaler.yaml
  - pod-disruption-budget.yaml
patches:
  - path: deployment-patch.yaml
images:
  - name: rushi412/social-platform-app
    newTag: replace-with-immutable-tag
